# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'RecipeCalc' do
use_frameworks!

pod "Firebase/Database"
pod "Firebase/Crash"
pod "Firebase/Auth"

pod "Material"

end
