# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'line count app' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for line count app

pod "Firebase"
pod "Firebase/Database"
pod "Firebase/Crash"
pod "Firebase/Auth"
pod "Firebase/AdMob"
pod "Firebase/Storage"

pod "FBSDKLoginKit"

pod "Material"

pod "IQKeyboardManagerSwift"

# https://github.com/hyperoslo/ImagePicker
pod "ImagePicker"

# https://github.com/justwudi/WDStarRatingView
pod 'HMWDStarRatingView', '~> 0.4'

# https://cocoapods.org/pods/Refresher
pod 'Refresher', '~> 0.5'

# https://cocoapods.org/pods/MRConfirmationAlertView
pod "MRConfirmationAlertView"

  target 'line count appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'line count appUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
