platform :ios, '8.0'
use_frameworks!
target 'recipeCalc' do

pod "Firebase"
pod "Firebase/Database"
pod "Firebase/Crash"
pod "Firebase/Auth"

pod "Material"

pod "IQKeyboardManagerSwift"

# https://github.com/justwudi/WDStarRatingView
pod 'HMWDStarRatingView', '~> 0.4'

# https://cocoapods.org/pods/Refresher
pod 'Refresher', '~> 0.5'

# https://cocoapods.org/pods/SlackTextViewController
# pod 'SlackTextViewController', '~> 1.9'
# pod try SlackTextViewController

end